export enum FLOGO_TASK_TYPE {
  TASK_ROOT, // this is the type for triggers
  TASK = 1,
}

export const FLOGO_ERROR_ROOT_NAME = '__error-trigger';

export const TRIGGER_MENU_OPERATION = {
  SHOW_SETTINGS: 'show-settings',
  DELETE: 'delete',
};

const TYPE_ATTR_ASSIGNMENT = 1;
const TYPE_LITERAL_ASSIGNMENT = 2;
const TYPE_EXPRESSION_ASSIGNMENT = 3;
const TYPE_OBJECT_TEMPLATE = 4;
export const MAPPING_TYPE = {
  ATTR_ASSIGNMENT: TYPE_ATTR_ASSIGNMENT,
  LITERAL_ASSIGNMENT: TYPE_LITERAL_ASSIGNMENT,
  EXPRESSION_ASSIGNMENT: TYPE_EXPRESSION_ASSIGNMENT,
  OBJECT_TEMPLATE: TYPE_OBJECT_TEMPLATE,
};
